packages:
  - packages/*
  - evaluations/*

catalog:
  oxfmt: 0.55.0

catalogMode: strict

cleanupUnusedCatalogs: true

minimumReleaseAge: 4320

savePrefix: ''

sideEffectsCache: false

strictDepBuilds: true

verifyDepsBeforeRun: prompt
