packages:
  - packages/*
  - evaluations/*

catalog:
  "@eslint/js": 9.39.2
  eslint: 9.39.2
  oxfmt: 0.55.0

catalogMode: strict

cleanupUnusedCatalogs: true

minimumReleaseAge: 4320

onlyBuiltDependencies:
  - esbuild

savePrefix: ""

sideEffectsCache: false

strictDepBuilds: true

verifyDepsBeforeRun: prompt